artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_url: https://storage.googleapis.com/ztm_tf_course/food_vision/10_food_classes_10_percent.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion  

data_loader:
  root_dir: artifacts/data_ingestion/10_food_classes_10_percent
  train_dir: artifacts/data_ingestion/10_food_classes_10_percent/train
  test_dir: artifacts/data_ingestion/10_food_classes_10_percent/test